# Insurance Claim Resampling Techniques

In [9]:
import warnings
warnings.filterwarnings('ignore')

In [10]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [11]:
columns = [
    "months_as_customer","age","policy_state","policy_csl","policy_deductable",
    "policy_annual_premium", "umbrella_limit","insured_zip", "insured_sex","insured_education_level","insured_occupation",
    "insured_relationship","capital-gains","capital-loss","incident_date","incident_type","collision_type",
    "incident_severity","authorities_contacted","incident_state","incident_city","incident_location",
    "incident_hour_of_the_day","number_of_vehicles_involved","property_damage","bodily_injuries","witnesses",
    "police_report_available","total_claim_amount","injury_claim","property_claim","vehicle_claim","auto_make","auto_model",
    "auto_year"
]

target = ["fraud_reported"]

In [12]:
# Load the data
file_path = Path('Resources/insurance_claims.csv')
df = pd.read_csv(file_path)
df = df.drop(["policy_number", "policy_bind_date","insured_hobbies"], axis=1)

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

df.head()

months_as_customer  age policy_state policy_csl  policy_deductable  \
0                 328   48           OH    250/500               1000   
1                 228   42           IN    250/500               2000   
2                 134   29           OH    100/300               2000   
3                 256   41           IL    250/500               2000   
4                 228   44           IL   500/1000               1000   

   policy_annual_premium  umbrella_limit  insured_zip insured_sex  \
0                1406.91               0       466132        MALE   
1                1197.22         5000000       468176        MALE   
2                1413.14         5000000       430632      FEMALE   
3                1415.74         6000000       608117      FEMALE   
4                1583.91         6000000       610706        MALE   

  insured_education_level  ... witnesses police_report_available  \
0                      MD  ...         2                     YES   
1                      MD  ...         0                       ?   
2                     PhD  ...         3                      NO   
3                     PhD  ...         2                      NO   
4               Associate  ...         1                      NO   

   total_claim_amount  injury_claim property_claim vehicle_claim  auto_make  \
0               71610          6510          13020         52080       Saab   
1                5070           780            780          3510   Mercedes   
2               34650          7700           3850         23100      Dodge   
3               63400          6340           6340         50720  Chevrolet   
4                6500          1300            650          4550     Accura   

  auto_model auto_year fraud_reported  
0        92x      2004              Y  
1       E400      2007              Y  
2        RAM      2007              N  
3      Tahoe      2014              Y  
4        RSX      2009              N  

[5 rows x 36 columns]

# Split the Data into Training and Testing

In [13]:
# Create our features
X = df.drop("fraud_reported", axis=1)
X = pd.get_dummies(X)

# Create our target
y = df["fraud_reported"]

In [14]:
X.describe()

months_as_customer          age  policy_deductable  \
count         1000.000000  1000.000000        1000.000000   
mean           203.954000    38.948000        1136.000000   
std            115.113174     9.140287         611.864673   
min              0.000000    19.000000         500.000000   
25%            115.750000    32.000000         500.000000   
50%            199.500000    38.000000        1000.000000   
75%            276.250000    44.000000        2000.000000   
max            479.000000    64.000000        2000.000000   

       policy_annual_premium  umbrella_limit    insured_zip  capital-gains  \
count            1000.000000    1.000000e+03    1000.000000    1000.000000   
mean             1256.406150    1.101000e+06  501214.488000   25126.100000   
std               244.167395    2.297407e+06   71701.610941   27872.187708   
min               433.330000   -1.000000e+06  430104.000000       0.000000   
25%              1089.607500    0.000000e+00  448404.500000       0.000000   
50%              1257.200000    0.000000e+00  466445.500000       0.000000   
75%              1415.695000    0.000000e+00  603251.000000   51025.000000   
max              2047.590000    1.000000e+07  620962.000000  100500.000000   

        capital-loss  incident_hour_of_the_day  number_of_vehicles_involved  \
count    1000.000000               1000.000000                   1000.00000   
mean   -26793.700000                 11.644000                      1.83900   
std     28104.096686                  6.951373                      1.01888   
min   -111100.000000                  0.000000                      1.00000   
25%    -51500.000000                  6.000000                      1.00000   
50%    -23250.000000                 12.000000                      1.00000   
75%         0.000000                 17.000000                      3.00000   
max         0.000000                 23.000000                      4.00000   

       ...  auto_model_Pathfinder  auto_model_RAM  auto_model_RSX  \
count  ...            1000.000000     1000.000000      1000.00000   
mean   ...               0.031000        0.043000         0.01200   
std    ...               0.173404        0.202959         0.10894   
min    ...               0.000000        0.000000         0.00000   
25%    ...               0.000000        0.000000         0.00000   
50%    ...               0.000000        0.000000         0.00000   
75%    ...               0.000000        0.000000         0.00000   
max    ...               1.000000        1.000000         1.00000   

       auto_model_Silverado  auto_model_TL  auto_model_Tahoe  \
count           1000.000000     1000.00000       1000.000000   
mean               0.022000        0.02000          0.024000   
std                0.146757        0.14007          0.153126   
min                0.000000        0.00000          0.000000   
25%                0.000000        0.00000          0.000000   
50%                0.000000        0.00000          0.000000   
75%                0.000000        0.00000          0.000000   
max                1.000000        1.00000          1.000000   

       auto_model_Ultima  auto_model_Wrangler  auto_model_X5  auto_model_X6  
count        1000.000000           1000.00000    1000.000000    1000.000000  
mean            0.023000              0.04200       0.023000       0.016000  
std             0.149978              0.20069       0.149978       0.125538  
min             0.000000              0.00000       0.000000       0.000000  
25%             0.000000              0.00000       0.000000       0.000000  
50%             0.000000              0.00000       0.000000       0.000000  
75%             0.000000              0.00000       0.000000       0.000000  
max             1.000000              1.00000       1.000000       1.000000  

[8 rows x 1202 columns]

In [15]:
# Check the balance of our target values
y.value_counts()

N    753
Y    247
Name: fraud_reported, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
print ("Training:")
print(y_train.value_counts())
print ("Test:")
print(y_test.value_counts())

Training:
N    570
Y    180
Name: fraud_reported, dtype: int64
Test:
N    183
Y     67
Name: fraud_reported, dtype: int64


# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [18]:
# Create our features
X = df.drop("fraud_reported", axis=1)
X = pd.get_dummies(X)

# Create our target
y = df.loc[:, target].copy()

In [19]:
X.describe()

months_as_customer          age  policy_deductable  \
count         1000.000000  1000.000000        1000.000000   
mean           203.954000    38.948000        1136.000000   
std            115.113174     9.140287         611.864673   
min              0.000000    19.000000         500.000000   
25%            115.750000    32.000000         500.000000   
50%            199.500000    38.000000        1000.000000   
75%            276.250000    44.000000        2000.000000   
max            479.000000    64.000000        2000.000000   

       policy_annual_premium  umbrella_limit    insured_zip  capital-gains  \
count            1000.000000    1.000000e+03    1000.000000    1000.000000   
mean             1256.406150    1.101000e+06  501214.488000   25126.100000   
std               244.167395    2.297407e+06   71701.610941   27872.187708   
min               433.330000   -1.000000e+06  430104.000000       0.000000   
25%              1089.607500    0.000000e+00  448404.500000       0.000000   
50%              1257.200000    0.000000e+00  466445.500000       0.000000   
75%              1415.695000    0.000000e+00  603251.000000   51025.000000   
max              2047.590000    1.000000e+07  620962.000000  100500.000000   

        capital-loss  incident_hour_of_the_day  number_of_vehicles_involved  \
count    1000.000000               1000.000000                   1000.00000   
mean   -26793.700000                 11.644000                      1.83900   
std     28104.096686                  6.951373                      1.01888   
min   -111100.000000                  0.000000                      1.00000   
25%    -51500.000000                  6.000000                      1.00000   
50%    -23250.000000                 12.000000                      1.00000   
75%         0.000000                 17.000000                      3.00000   
max         0.000000                 23.000000                      4.00000   

       ...  auto_model_Pathfinder  auto_model_RAM  auto_model_RSX  \
count  ...            1000.000000     1000.000000      1000.00000   
mean   ...               0.031000        0.043000         0.01200   
std    ...               0.173404        0.202959         0.10894   
min    ...               0.000000        0.000000         0.00000   
25%    ...               0.000000        0.000000         0.00000   
50%    ...               0.000000        0.000000         0.00000   
75%    ...               0.000000        0.000000         0.00000   
max    ...               1.000000        1.000000         1.00000   

       auto_model_Silverado  auto_model_TL  auto_model_Tahoe  \
count           1000.000000     1000.00000       1000.000000   
mean               0.022000        0.02000          0.024000   
std                0.146757        0.14007          0.153126   
min                0.000000        0.00000          0.000000   
25%                0.000000        0.00000          0.000000   
50%                0.000000        0.00000          0.000000   
75%                0.000000        0.00000          0.000000   
max                1.000000        1.00000          1.000000   

       auto_model_Ultima  auto_model_Wrangler  auto_model_X5  auto_model_X6  
count        1000.000000           1000.00000    1000.000000    1000.000000  
mean            0.023000              0.04200       0.023000       0.016000  
std             0.149978              0.20069       0.149978       0.125538  
min             0.000000              0.00000       0.000000       0.000000  
25%             0.000000              0.00000       0.000000       0.000000  
50%             0.000000              0.00000       0.000000       0.000000  
75%             0.000000              0.00000       0.000000       0.000000  
max             1.000000              1.00000       1.000000       1.000000  

[8 rows x 1202 columns]

In [20]:
# Check the balance of our target values
y['fraud_reported'].value_counts()

N    753
Y    247
Name: fraud_reported, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
print("Training:",Counter(y_train['fraud_reported']))
print("Test:",Counter(y_test['fraud_reported']))

Training: Counter({'N': 573, 'Y': 177})
Test: Counter({'N': 180, 'Y': 70})


In [22]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
print(Counter(y_resampled['fraud_reported']))

Counter({'N': 573, 'Y': 573})


In [23]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [24]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5555555555555556

In [25]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[92, 88],
       [28, 42]], dtype=int64)

In [26]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          N       0.77      0.51      0.60      0.61      0.55      0.30       180
          Y       0.32      0.60      0.51      0.42      0.55      0.31        70

avg / total       0.64      0.54      0.58      0.56      0.55      0.31       250



### SMOTE Oversampling

In [27]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(
   X_train, y_train)

In [28]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [29]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.5988095238095239

In [30]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[105,  75],
       [ 27,  43]], dtype=int64)

In [31]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          N       0.80      0.58      0.61      0.67      0.60      0.36       180
          Y       0.36      0.61      0.58      0.46      0.60      0.36        70

avg / total       0.67      0.59      0.61      0.61      0.60      0.36       250



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [32]:
# Resample the data using the ClusterCentroids resampler
from collections import Counter
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({'fraud_reported': 1})

In [33]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [34]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.5988095238095239

In [35]:
# Display the confusion matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 79, 101],
       [ 22,  48]], dtype=int64)

In [36]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          N       0.78      0.44      0.69      0.56      0.55      0.29       180
          Y       0.32      0.69      0.44      0.44      0.55      0.31        70

avg / total       0.65      0.51      0.62      0.53      0.55      0.30       250



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [38]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)
Counter(y_resampled)

Counter({'fraud_reported': 1})

In [39]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [40]:
# Calculated the balanced accuracy score
balanced_accuracy_score(y_test, y_pred)

0.5623015873015873

In [41]:
# Display the confusion matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 57, 123],
       [ 10,  60]], dtype=int64)

In [42]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          N       0.85      0.32      0.86      0.46      0.52      0.26       180
          Y       0.33      0.86      0.32      0.47      0.52      0.29        70

avg / total       0.70      0.47      0.71      0.47      0.52      0.26       250

